version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: ./compose/consumer/Dockerfile
    # volumes:
    #   - .:/app
    # depends_on:
    #   - db
    #   - rabbitmq
    #   - redis
    environment:  # TODO mv to .env
      AMQP_URL: 'amqp://rmuser:rmpassword@rabbitmq:5672'
      POSTGRES_URL: "postgresql://postgres:postgres@db:5432/"
      APOSTGRES_URL: "postgresql+asyncpg://postgres:postgres@db:5432/"
      REDIS_URL: "redis://redis:6379"
      QUEUE_N: 4
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: 'rabbitmq:3.12.7-management'
    hostname: "rabbitmq"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'rmuser'
      RABBITMQ_DEFAULT_PASS: 'rmpassword'

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
