version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: ./compose/consumer/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: 'amqp://rmuser:rmpassword@rabbitmq-container:5672/?connection_attempts=3&retry_delay=5'
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  rabbitmq:
    image: 'rabbitmq:3.12.7'
    hostname: rabbitmq-container
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - resolute
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'rmuser'
      RABBITMQ_DEFAULT_PASS: 'rmpassword'

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  resolute:
    external: true
    name: resolute
